language: ruby
rvm:
  - 1.9.3
before_script:
  - ./bin/travis-before-script.rb
notifications:
  email:
    - bgadoury@endpoint.com
services:
  - elasticsearch
branches:
  only:
    - develop
    - travisfix

